<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class dataHtmlSeeder extends Seeder
{
    public $questions_html = [];
    public $essays_html = [];

    public function __construct()
    {
        $this->questions_html =
            [
                [
                    'question' => 'Từ HTML là từ viết tắt của từ nào?',
                    'option_1' => 'Hyperlinks and Text Markup Language',
                    'option_2' => 'Home Tool Markup Language',
                    'option_3' => 'Hyper Text Markup Language',
                    'option_4' => 'Tất cả đều sai',
                    'answer' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo đoạn văn bản?',
                    'option_1' => '<p>',
                    'option_2' => '<a>',
                    'option_3' => '<div>',
                    'option_4' => '<span>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo liên kết?',
                    'option_1' => '<link>',
                    'option_2' => '<a>',
                    'option_3' => '<href>',
                    'option_4' => '<url>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ nào được sử dụng để chèn hình ảnh vào HTML?',
                    'option_1' => '<img>',
                    'option_2' => '<picture>',
                    'option_3' => '<src>',
                    'option_4' => '<figure>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo tiêu đề cấp 1?',
                    'option_1' => '<head>',
                    'option_2' => '<header>',
                    'option_3' => '<h1>',
                    'option_4' => '<title>',
                    'answer' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào được dùng để đặt tên cho một thẻ HTML?',
                    'option_1' => 'class',
                    'option_2' => 'id',
                    'option_3' => 'name',
                    'option_4' => 'tag',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo danh sách không có thứ tự?',
                    'option_1' => '<ol>',
                    'option_2' => '<ul>',
                    'option_3' => '<li>',
                    'option_4' => '<dl>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo danh sách có thứ tự?',
                    'option_1' => '<ol>',
                    'option_2' => '<ul>',
                    'option_3' => '<li>',
                    'option_4' => '<dl>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một ô trong bảng?',
                    'option_1' => '<cell>',
                    'option_2' => '<td>',
                    'option_3' => '<tr>',
                    'option_4' => '<table>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một hàng trong bảng?',
                    'option_1' => '<tr>',
                    'option_2' => '<td>',
                    'option_3' => '<table>',
                    'option_4' => '<row>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để định nghĩa URL của hình ảnh trong thẻ <img>?',
                    'option_1' => 'src',
                    'option_2' => 'href',
                    'option_3' => 'url',
                    'option_4' => 'link',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo form?',
                    'option_1' => '<form>',
                    'option_2' => '<input>',
                    'option_3' => '<button>',
                    'option_4' => '<label>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào được dùng để định nghĩa đường dẫn của liên kết?',
                    'option_1' => 'src',
                    'option_2' => 'href',
                    'option_3' => 'url',
                    'option_4' => 'link',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một đoạn trích dẫn dài?',
                    'option_1' => '<blockquote>',
                    'option_2' => '<quote>',
                    'option_3' => '<cite>',
                    'option_4' => '<q>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để nhấn mạnh văn bản?',
                    'option_1' => '<strong>',
                    'option_2' => '<em>',
                    'option_3' => '<i>',
                    'option_4' => '<b>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một checkbox trong form?',
                    'option_1' => '<input type="checkbox">',
                    'option_2' => '<input type="radio">',
                    'option_3' => '<input type="text">',
                    'option_4' => '<input type="button">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một nút bấm?',
                    'option_1' => '<button>',
                    'option_2' => '<input>',
                    'option_3' => '<form>',
                    'option_4' => '<label>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một trường nhập văn bản trong form?',
                    'option_1' => '<input type="text">',
                    'option_2' => '<input type="password">',
                    'option_3' => '<input type="submit">',
                    'option_4' => '<input type="checkbox">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một đoạn trích dẫn ngắn?',
                    'option_1' => '<quote>',
                    'option_2' => '<q>',
                    'option_3' => '<cite>',
                    'option_4' => '<blockquote>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để định nghĩa phần đầu của tài liệu?',
                    'option_1' => '<head>',
                    'option_2' => '<header>',
                    'option_3' => '<h1>',
                    'option_4' => '<title>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để định nghĩa phần nội dung chính của tài liệu?',
                    'option_1' => '<main>',
                    'option_2' => '<body>',
                    'option_3' => '<content>',
                    'option_4' => '<section>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một danh sách định nghĩa?',
                    'option_1' => '<dl>',
                    'option_2' => '<ol>',
                    'option_3' => '<ul>',
                    'option_4' => '<li>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một mục trong danh sách định nghĩa?',
                    'option_1' => '<dt>',
                    'option_2' => '<dd>',
                    'option_3' => '<li>',
                    'option_4' => '<dl>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một mục định nghĩa trong danh sách định nghĩa?',
                    'option_1' => '<dl>',
                    'option_2' => '<dd>',
                    'option_3' => '<dt>',
                    'option_4' => '<li>',
                    'answer' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng chứa div?',
                    'option_1' => '<div>',
                    'option_2' => '<span>',
                    'option_3' => '<section>',
                    'option_4' => '<article>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một đoạn ngắn inline?',
                    'option_1' => '<span>',
                    'option_2' => '<div>',
                    'option_3' => '<section>',
                    'option_4' => '<article>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để xác định chiều rộng của một thẻ HTML?',
                    'option_1' => 'height',
                    'option_2' => 'width',
                    'option_3' => 'size',
                    'option_4' => 'length',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để xác định chiều cao của một thẻ HTML?',
                    'option_1' => 'width',
                    'option_2' => 'height',
                    'option_3' => 'size',
                    'option_4' => 'length',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một liên kết điều hướng?',
                    'option_1' => '<a>',
                    'option_2' => '<link>',
                    'option_3' => '<nav>',
                    'option_4' => '<ul>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một bảng?',
                    'option_1' => '<table>',
                    'option_2' => '<tr>',
                    'option_3' => '<td>',
                    'option_4' => '<th>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để xác định nguồn gốc của một hình ảnh?',
                    'option_1' => 'href',
                    'option_2' => 'src',
                    'option_3' => 'alt',
                    'option_4' => 'link',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để định nghĩa văn bản thay thế cho một hình ảnh?',
                    'option_1' => 'src',
                    'option_2' => 'alt',
                    'option_3' => 'href',
                    'option_4' => 'title',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một danh sách định nghĩa?',
                    'option_1' => '<dl>',
                    'option_2' => '<ol>',
                    'option_3' => '<ul>',
                    'option_4' => '<li>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo phần chân của trang?',
                    'option_1' => '<footer>',
                    'option_2' => '<foot>',
                    'option_3' => '<bottom>',
                    'option_4' => '<end>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo phần điều hướng của trang?',
                    'option_1' => '<nav>',
                    'option_2' => '<navigate>',
                    'option_3' => '<menu>',
                    'option_4' => '<list>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo phần thân của tài liệu?',
                    'option_1' => '<body>',
                    'option_2' => '<main>',
                    'option_3' => '<content>',
                    'option_4' => '<section>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo phần đầu của tài liệu?',
                    'option_1' => '<head>',
                    'option_2' => '<header>',
                    'option_3' => '<h1>',
                    'option_4' => '<title>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào dùng để xác định màu nền của một thẻ HTML?',
                    'option_1' => 'color',
                    'option_2' => 'background-color',
                    'option_3' => 'bgcolor',
                    'option_4' => 'style',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một đoạn văn?',
                    'option_1' => '<p>',
                    'option_2' => '<div>',
                    'option_3' => '<span>',
                    'option_4' => '<section>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để nhúng một tài liệu HTML vào một tài liệu HTML khác?',
                    'option_1' => '<iframe>',
                    'option_2' => '<frame>',
                    'option_3' => '<embed>',
                    'option_4' => '<object>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định metadata cho một tài liệu?',
                    'option_1' => '<meta>',
                    'option_2' => '<link>',
                    'option_3' => '<script>',
                    'option_4' => '<style>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để nhúng video vào trang web?',
                    'option_1' => '<video>',
                    'option_2' => '<media>',
                    'option_3' => '<embed>',
                    'option_4' => '<object>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để nhúng âm thanh vào trang web?',
                    'option_1' => '<audio>',
                    'option_2' => '<sound>',
                    'option_3' => '<embed>',
                    'option_4' => '<object>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định một tập hợp các chỉ dẫn?',
                    'option_1' => '<datalist>',
                    'option_2' => '<select>',
                    'option_3' => '<input>',
                    'option_4' => '<option>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để gửi dữ liệu theo phương thức POST?',
                    'option_1' => 'method="send"',
                    'option_2' => 'method="post"',
                    'option_3' => 'type="post"',
                    'option_4' => 'send="post"',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để xác định URL đích nhận dữ liệu?',
                    'option_1' => 'action',
                    'option_2' => 'method',
                    'option_3' => 'target',
                    'option_4' => 'enctype',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để định nghĩa các thông tin thêm về một phần tử khi người dùng di chuột qua?',
                    'option_1' => 'title',
                    'option_2' => 'tooltip',
                    'option_3' => 'hover',
                    'option_4' => 'popup',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng chọn nhiều dòng?',
                    'option_1' => '<textarea>',
                    'option_2' => '<input type="textarea">',
                    'option_3' => '<input type="text">',
                    'option_4' => '<select>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <input> để tạo một trường nhập liệu ẩn?',
                    'option_1' => 'type="hidden"',
                    'option_2' => 'type="invisible"',
                    'option_3' => 'hidden="true"',
                    'option_4' => 'visible="false"',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để nhúng một tệp SVG vào tài liệu HTML?',
                    'option_1' => '<svg>',
                    'option_2' => '<img>',
                    'option_3' => '<object>',
                    'option_4' => '<embed>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một thực đơn ngữ cảnh khi nhấp chuột phải?',
                    'option_1' => '<contextmenu>',
                    'option_2' => '<menu>',
                    'option_3' => '<rightclick>',
                    'option_4' => '<dropdown>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để nhúng một tài liệu PDF vào trang web?',
                    'option_1' => '<embed>',
                    'option_2' => '<object>',
                    'option_3' => '<iframe>',
                    'option_4' => '<pdf>',
                    'answer' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <input> để chấp nhận nhiều tệp?',
                    'option_1' => 'multiple',
                    'option_2' => 'files',
                    'option_3' => 'multifile',
                    'option_4' => 'many',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng nhập liệu màu sắc?',
                    'option_1' => '<input type="color">',
                    'option_2' => '<input type="palette">',
                    'option_3' => '<input type="rgb">',
                    'option_4' => '<input type="hue">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng nhập liệu ngày tháng?',
                    'option_1' => '<input type="date">',
                    'option_2' => '<input type="datetime">',
                    'option_3' => '<input type="calendar">',
                    'option_4' => '<input type="time">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng nhập liệu số?',
                    'option_1' => '<input type="number">',
                    'option_2' => '<input type="numeric">',
                    'option_3' => '<input type="value">',
                    'option_4' => '<input type="digit">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng nhập liệu phạm vi?',
                    'option_1' => '<input type="range">',
                    'option_2' => '<input type="slider">',
                    'option_3' => '<input type="scale">',
                    'option_4' => '<input type="bar">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng nhập liệu email?',
                    'option_1' => '<input type="email">',
                    'option_2' => '<input type="mail">',
                    'option_3' => '<input type="address">',
                    'option_4' => '<input type="contact">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để mã hóa dữ liệu khi gửi?',
                    'option_1' => 'enctype',
                    'option_2' => 'encoding',
                    'option_3' => 'encrypt',
                    'option_4' => 'codetype',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <img> để xác định văn bản thay thế khi hình ảnh không tải được?',
                    'option_1' => 'alt',
                    'option_2' => 'title',
                    'option_3' => 'src',
                    'option_4' => 'fallback',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định một kết quả đo lường (ví dụ: nhiệt độ, tốc độ, v.v.)?',
                    'option_1' => '<meter>',
                    'option_2' => '<gauge>',
                    'option_3' => '<scale>',
                    'option_4' => '<measure>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để ngăn chặn việc gửi tự động khi người dùng nhấn Enter?',
                    'option_1' => 'novalidate',
                    'option_2' => 'onsubmit',
                    'option_3' => 'action',
                    'option_4' => 'method',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định thông tin chi tiết mà người dùng có thể xem hoặc ẩn?',
                    'option_1' => '<details>',
                    'option_2' => '<summary>',
                    'option_3' => '<info>',
                    'option_4' => '<tooltip>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định tiêu đề cho phần tử <details>?',
                    'option_1' => '<summary>',
                    'option_2' => '<details>',
                    'option_3' => '<title>',
                    'option_4' => '<caption>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định kết quả đo lường (ví dụ: thanh tiến trình)?',
                    'option_1' => '<progress>',
                    'option_2' => '<meter>',
                    'option_3' => '<range>',
                    'option_4' => '<gauge>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để nhúng nội dung bên ngoài như video hoặc flash vào trang web?',
                    'option_1' => '<embed>',
                    'option_2' => '<object>',
                    'option_3' => '<iframe>',
                    'option_4' => '<media>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để xác định loại mã hóa dữ liệu khi gửi qua phương thức POST?',
                    'option_1' => 'enctype',
                    'option_2' => 'encoding',
                    'option_3' => 'method',
                    'option_4' => 'action',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để xác định một phần tử điều khiển mà người dùng có thể tương tác?',
                    'option_1' => '<input>',
                    'option_2' => '<form>',
                    'option_3' => '<button>',
                    'option_4' => '<label>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <form> để xác định URL nơi dữ liệu sẽ được gửi?',
                    'option_1' => 'action',
                    'option_2' => 'method',
                    'option_3' => 'enctype',
                    'option_4' => 'target',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một vùng chọn ngày và giờ?',
                    'option_1' => '<input type="datetime-local">',
                    'option_2' => '<input type="date">',
                    'option_3' => '<input type="time">',
                    'option_4' => '<input type="datetime">',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <img> để xác định tệp hình ảnh mà phải hiển thị khi hình ảnh không tải được?',
                    'option_1' => 'alt',
                    'option_2' => 'src',
                    'option_3' => 'onerror',
                    'option_4' => 'fallback',
                    'answer' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau đây có chức năng gì?<br><code>&lt;input type="text" name="username" required pattern="[A-Za-z0-9]{5,10}"&gt;</code>',
                    'option_1' => 'Yêu cầu người dùng nhập tên đăng nhập từ 5 đến 10 ký tự chữ cái hoặc số.',
                    'option_2' => 'Yêu cầu người dùng nhập tên đăng nhập ít nhất 5 ký tự và nhiều nhất 10 ký tự bất kỳ.',
                    'option_3' => 'Yêu cầu người dùng nhập tên đăng nhập chỉ gồm các ký tự chữ cái hoặc số.',
                    'option_4' => 'Yêu cầu người dùng nhập tên đăng nhập từ 5 đến 10 ký tự chữ cái hoặc số, và không bắt buộc.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;link rel="preload" href="style.css" as="style"&gt;</code>',
                    'option_1' => 'Tải trước tệp style.css để cải thiện tốc độ tải trang.',
                    'option_2' => 'Chỉ định rằng style.css là tệp CSS chính của trang.',
                    'option_3' => 'Chỉ định rằng style.css sẽ được tải sau khi trang hoàn tất tải.',
                    'option_4' => 'Không có tác dụng gì.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để tạo một mẫu biểu mẫu định nghĩa?',
                    'option_1' => '<template>',
                    'option_2' => '<form>',
                    'option_3' => '<pattern>',
                    'option_4' => '<fieldset>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau sẽ hiển thị gì?<br><code>&lt;style&gt;div { display: none; }&lt;/style&gt;&lt;div&gt;Hello&lt;/div&gt;</code>',
                    'option_1' => 'Không hiển thị gì cả.',
                    'option_2' => 'Hiển thị chữ "Hello".',
                    'option_3' => 'Hiển thị chữ "div".',
                    'option_4' => 'Hiển thị chữ "Hello" trong thẻ div.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <a> để mở liên kết trong một cửa sổ mới hoặc tab mới?',
                    'option_1' => 'target="_blank"',
                    'option_2' => 'target="_new"',
                    'option_3' => 'window="new"',
                    'option_4' => 'rel="noopener"',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Công dụng của thuộc tính <code>contenteditable</code> trong thẻ HTML là gì?',
                    'option_1' => 'Cho phép nội dung của phần tử có thể chỉnh sửa.',
                    'option_2' => 'Chỉ định nội dung của phần tử có thể được sao chép.',
                    'option_3' => 'Chỉ định nội dung của phần tử không thể chỉnh sửa.',
                    'option_4' => 'Cho phép nội dung của phần tử có thể được xem.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có tác dụng gì?<br><code>&lt;!DOCTYPE html&gt;</code>',
                    'option_1' => 'Xác định tài liệu là tài liệu HTML5.',
                    'option_2' => 'Xác định tài liệu là tài liệu HTML4.',
                    'option_3' => 'Không có tác dụng gì.',
                    'option_4' => 'Xác định tài liệu là tài liệu XML.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>srcset</code> của thẻ <code>&lt;img&gt;</code> có chức năng gì?',
                    'option_1' => 'Chỉ định danh sách các tệp hình ảnh có độ phân giải khác nhau để trình duyệt có thể chọn tùy theo kích thước màn hình.',
                    'option_2' => 'Chỉ định tệp hình ảnh thay thế khi tệp hình ảnh chính không tải được.',
                    'option_3' => 'Chỉ định danh sách các tệp hình ảnh để tải đồng thời.',
                    'option_4' => 'Chỉ định tệp video liên quan đến tệp hình ảnh.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;div style="position: absolute; left: 50%; top: 50%;"&gt;&lt;/div&gt;</code>',
                    'option_1' => 'Đặt phần tử div ở giữa trang.',
                    'option_2' => 'Đặt phần tử div ở góc trên bên trái trang.',
                    'option_3' => 'Đặt phần tử div ở góc dưới bên phải trang.',
                    'option_4' => 'Không có tác dụng gì.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để định nghĩa một vùng có thể kéo và thả?',
                    'option_1' => '<drag>',
                    'option_2' => '<draggable>',
                    'option_3' => '<drop>',
                    'option_4' => '<div draggable="true">',
                    'answer' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính nào của thẻ <video> để chỉ định tệp video sẽ tự động phát khi trang được tải?',
                    'option_1' => 'autoplay',
                    'option_2' => 'controls',
                    'option_3' => 'loop',
                    'option_4' => 'muted',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để xác định một tập hợp các tùy chọn có thể được lựa chọn trong một hộp lựa chọn?',
                    'option_1' => '<optgroup>',
                    'option_2' => '<option>',
                    'option_3' => '<select>',
                    'option_4' => '<datalist>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;meta charset="UTF-8"&gt;</code>',
                    'option_1' => 'Đặt bộ ký tự của tài liệu là UTF-8.',
                    'option_2' => 'Đặt ngôn ngữ của tài liệu là UTF-8.',
                    'option_3' => 'Không có tác dụng gì.',
                    'option_4' => 'Đặt định dạng của tài liệu là UTF-8.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào được sử dụng để xác định một chú thích cho bảng?',
                    'option_1' => '<caption>',
                    'option_2' => '<summary>',
                    'option_3' => '<legend>',
                    'option_4' => '<title>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có tác dụng gì?<br><code>&lt;div contenteditable="true"&gt;&lt;/div&gt;</code>',
                    'option_1' => 'Cho phép nội dung của thẻ div có thể chỉnh sửa.',
                    'option_2' => 'Cho phép nội dung của thẻ div có thể sao chép.',
                    'option_3' => 'Không có tác dụng gì.',
                    'option_4' => 'Cho phép nội dung của thẻ div không thể chỉnh sửa.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>defer</code> của thẻ <script> có chức năng gì?',
                    'option_1' => 'Chỉ định rằng kịch bản sẽ được thực thi sau khi tài liệu đã được phân tích cú pháp hoàn toàn.',
                    'option_2' => 'Chỉ định rằng kịch bản sẽ được thực thi ngay khi nó được tải.',
                    'option_3' => 'Chỉ định rằng kịch bản sẽ được tải không đồng bộ.',
                    'option_4' => 'Chỉ định rằng kịch bản sẽ được thực thi trước khi tài liệu được phân tích cú pháp.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;</code>',
                    'option_1' => 'Đặt tỷ lệ ban đầu của trang để phù hợp với kích thước thiết bị.',
                    'option_2' => 'Đặt tỷ lệ ban đầu của trang để phù hợp với kích thước cửa sổ trình duyệt.',
                    'option_3' => 'Đặt bộ ký tự của trang là UTF-8.',
                    'option_4' => 'Không có tác dụng gì.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có tác dụng gì?<br><code>&lt;iframe src="page.html" width="600" height="400"&gt;&lt;/iframe&gt;</code>',
                    'option_1' => 'Nhúng tệp page.html vào trong một khung có chiều rộng 600 và chiều cao 400.',
                    'option_2' => 'Nhúng tệp page.html vào trong một cửa sổ trình duyệt mới có chiều rộng 600 và chiều cao 400.',
                    'option_3' => 'Nhúng tệp page.html vào trong một khung có chiều rộng và chiều cao mặc định.',
                    'option_4' => 'Nhúng tệp page.html vào trong một thẻ div có chiều rộng 600 và chiều cao 400.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>integrity</code> của thẻ <script> có chức năng gì?',
                    'option_1' => 'Đảm bảo rằng tệp kịch bản không bị thay đổi bằng cách kiểm tra giá trị băm của nó.',
                    'option_2' => 'Chỉ định rằng tệp kịch bản sẽ được tải không đồng bộ.',
                    'option_3' => 'Chỉ định rằng tệp kịch bản sẽ được thực thi sau khi tài liệu đã được phân tích cú pháp hoàn toàn.',
                    'option_4' => 'Chỉ định rằng tệp kịch bản sẽ được thực thi ngay khi nó được tải.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;style&gt; p { color: red; } &lt;/style&gt;&lt;p&gt;Hello&lt;/p&gt;</code>',
                    'option_1' => 'Hiển thị chữ "Hello" với màu đỏ.',
                    'option_2' => 'Hiển thị chữ "Hello" với màu đen.',
                    'option_3' => 'Hiển thị chữ "Hello" với màu mặc định.',
                    'option_4' => 'Không có tác dụng gì.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để xác định một thẻ bài viết độc lập?',
                    'option_1' => '<article>',
                    'option_2' => '<section>',
                    'option_3' => '<aside>',
                    'option_4' => '<header>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có tác dụng gì?<br><code>&lt;span style="display: block;"&gt;Hello&lt;/span&gt;</code>',
                    'option_1' => 'Hiển thị chữ "Hello" trên một dòng riêng biệt.',
                    'option_2' => 'Hiển thị chữ "Hello" trên cùng một dòng với các phần tử khác.',
                    'option_3' => 'Không hiển thị chữ "Hello".',
                    'option_4' => 'Hiển thị chữ "Hello" với màu mặc định.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>rel</code> của thẻ <link> có chức năng gì?',
                    'option_1' => 'Chỉ định mối quan hệ giữa tài liệu hiện tại và tài liệu được liên kết.',
                    'option_2' => 'Chỉ định tệp liên kết sẽ được tải không đồng bộ.',
                    'option_3' => 'Chỉ định tệp liên kết sẽ được thực thi sau khi tài liệu đã được phân tích cú pháp hoàn toàn.',
                    'option_4' => 'Chỉ định tệp liên kết sẽ được thực thi ngay khi nó được tải.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có tác dụng gì?<br><code>&lt;nav&gt;&lt;a href="index.html"&gt;Home&lt;/a&gt;&lt;/nav&gt;</code>',
                    'option_1' => 'Tạo một liên kết "Home" bên trong một thẻ điều hướng.',
                    'option_2' => 'Tạo một liên kết "Home" bên trong một thẻ div.',
                    'option_3' => 'Tạo một liên kết "Home" bên trong một thẻ header.',
                    'option_4' => 'Tạo một liên kết "Home" bên trong một thẻ footer.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>crossorigin</code> của thẻ <script> có chức năng gì?',
                    'option_1' => 'Chỉ định cách xử lý các yêu cầu nguồn gốc chéo cho tệp kịch bản.',
                    'option_2' => 'Chỉ định tệp kịch bản sẽ được tải không đồng bộ.',
                    'option_3' => 'Chỉ định tệp kịch bản sẽ được thực thi sau khi tài liệu đã được phân tích cú pháp hoàn toàn.',
                    'option_4' => 'Chỉ định tệp kịch bản sẽ được thực thi ngay khi nó được tải.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;footer&gt;Footer content&lt;/footer&gt;</code>',
                    'option_1' => 'Tạo một phần tử footer chứa nội dung "Footer content".',
                    'option_2' => 'Tạo một phần tử header chứa nội dung "Footer content".',
                    'option_3' => 'Tạo một phần tử div chứa nội dung "Footer content".',
                    'option_4' => 'Tạo một phần tử aside chứa nội dung "Footer content".',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để định nghĩa một phần tử chứa thông tin phụ thuộc vào ngữ cảnh?',
                    'option_1' => '<aside>',
                    'option_2' => '<section>',
                    'option_3' => '<footer>',
                    'option_4' => '<header>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Đoạn mã sau có chức năng gì?<br><code>&lt;style&gt; .hidden { display: none; } &lt;/style&gt;&lt;div class="hidden"&gt;Hidden content&lt;/div&gt;</code>',
                    'option_1' => 'Ẩn nội dung "Hidden content".',
                    'option_2' => 'Hiển thị nội dung "Hidden content".',
                    'option_3' => 'Hiển thị nội dung "Hidden content" với màu đỏ.',
                    'option_4' => 'Không có tác dụng gì.',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thẻ HTML nào dùng để xác định một thẻ điều hướng?',
                    'option_1' => '<nav>',
                    'option_2' => '<header>',
                    'option_3' => '<footer>',
                    'option_4' => '<section>',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'question' => 'Thuộc tính <code>type</code> của thẻ <button> có chức năng gì?',
                    'option_1' => 'Chỉ định kiểu của nút (button, submit, reset).',
                    'option_2' => 'Chỉ định kiểu của nút (button, checkbox, radio).',
                    'option_3' => 'Chỉ định kiểu của nút (button, link, image).',
                    'option_4' => 'Chỉ định kiểu của nút (button, text, password).',
                    'answer' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];
        $this->essays_html =
            [
                [
                    'question' => 'Thẻ [blank_1] được sử dụng để định nghĩa một tài liệu HTML.',
                    'blanks' => 'html',
                ],
                [
                    'question' => 'Thẻ [blank_1] chứa thông tin meta và các liên kết đến tài nguyên bên ngoài.',
                    'blanks' => 'head',
                ],
                [
                    'question' => 'Thẻ [blank_1] tạo tiêu đề lớn nhất và [blank_2] tạo tiêu đề nhỏ hơn.',
                    'blanks' => 'h1,h2',
                ],
                [
                    'question' => 'Thẻ [blank_1] được sử dụng để tạo liên kết đến trang web khác và thẻ [blank_2] dùng để mở liên kết trong cửa sổ mới.',
                    'blanks' => 'a,target',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa phần nội dung chính của tài liệu HTML.',
                    'blanks' => 'body',
                ],
                [
                    'question' => 'Thẻ [blank_1] được sử dụng để tạo danh sách không có thứ tự và thẻ [blank_2] để tạo mục trong danh sách đó.',
                    'blanks' => 'ul,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] được sử dụng để tạo bảng và thẻ [blank_2] định nghĩa hàng trong bảng.',
                    'blanks' => 'table,tr',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa cột tiêu đề và thẻ [blank_2] dùng để tạo ô dữ liệu trong bảng.',
                    'blanks' => 'th,td',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn hình ảnh và thuộc tính [blank_2] được sử dụng để xác định đường dẫn của hình ảnh.',
                    'blanks' => 'img,src',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa văn bản được bôi đậm và thẻ [blank_2] định nghĩa văn bản được làm nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] chèn một đường phân cách ngang và thẻ [blank_2] tạo một đoạn văn bản.',
                    'blanks' => 'hr,p',
                ],
                [
                    'question' => 'Thẻ [blank_1] được sử dụng để tạo tiêu đề cấp 3 và thẻ [blank_2] để tạo tiêu đề cấp 4.',
                    'blanks' => 'h3,h4',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn âm thanh và thẻ [blank_2] dùng để chèn video.',
                    'blanks' => 'audio,video',
                ],
                [
                    'question' => 'Thẻ [blank_1] tạo một khối văn bản và thẻ [blank_2] tạo một phần tử nội tuyến.',
                    'blanks' => 'div,span',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để thêm mã JavaScript vào trang và thẻ [blank_2] định nghĩa một đoạn mã.',
                    'blanks' => 'script,code',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chân và thẻ [blank_2] định nghĩa một khối văn bản có kiểu chữ gạch chéo.',
                    'blanks' => 'u,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn một khung iframe vào tài liệu và thẻ [blank_2] định nghĩa khu vực điều hướng.',
                    'blanks' => 'iframe,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khu vực chân của tài liệu và thẻ [blank_2] định nghĩa phần tiêu đề.',
                    'blanks' => 'footer,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một nhóm phần tử và thẻ [blank_2] dùng để định nghĩa nhóm liên kết.',
                    'blanks' => 'fieldset,legend',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một vùng chọn trong biểu mẫu và thẻ [blank_2] định nghĩa tùy chọn trong vùng chọn.',
                    'blanks' => 'select,option',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một ô nhập liệu văn bản và thẻ [blank_2] dùng để nhập nhiều dòng văn bản.',
                    'blanks' => 'input,textarea',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để liên kết đến tệp CSS và thẻ [blank_2] định nghĩa phần tử cho việc nhập nội dung văn bản.',
                    'blanks' => 'link,textarea',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có chú thích và thẻ [blank_2] định nghĩa phần văn bản được phân cách.',
                    'blanks' => 'mark,section',
                ],
                [
                    'question' => 'Thẻ [blank_1] tạo một khối văn bản được chèn vào từ một phần tử khác và thẻ [blank_2] dùng để tạo một khu vực chứa các phần tử.',
                    'blanks' => 'pre,main',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một nhóm liên kết điều hướng và thẻ [blank_2] tạo một khu vực cho phần tử.',
                    'blanks' => 'nav,section',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử văn bản và thẻ [blank_2] dùng để tạo một vùng chọn trong biểu mẫu.',
                    'blanks' => 'div,select',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một nhóm các mục trong danh sách không có thứ tự và thẻ [blank_2] dùng để định nghĩa một nhóm các phần tử văn bản.',
                    'blanks' => 'ul,div',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản gạch chân và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh.',
                    'blanks' => 'u,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử văn bản không có kiểu chữ và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ nghiêng.',
                    'blanks' => 'p,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa phần chân của tài liệu.',
                    'blanks' => 's,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa phần đầu trang của tài liệu và thẻ [blank_2] dùng để tạo một khu vực cho phần tử chính.',
                    'blanks' => 'header,main',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản được chèn vào từ một phần tử khác và thẻ [blank_2] dùng để tạo một danh sách không có thứ tự.',
                    'blanks' => 'pre,ul',
                ],
                [
                    'question' => 'Thẻ [blank_1] tạo một phần tử điều hướng và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ gạch chân.',
                    'blanks' => 'nav,u',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử HTML và thẻ [blank_2] dùng để định nghĩa một nhóm liên kết điều hướng.',
                    'blanks' => 'div,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có chú thích và thẻ [blank_2] dùng để định nghĩa một nhóm các mục trong danh sách.',
                    'blanks' => 'mark,ul',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử văn bản gạch chéo và thẻ [blank_2] định nghĩa phần tử nhập nội dung văn bản.',
                    'blanks' => 's,textarea',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản được bôi đậm và thẻ [blank_2] dùng để định nghĩa phần tử đầu trang của tài liệu.',
                    'blanks' => 'strong,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử văn bản không có kiểu chữ và thẻ [blank_2] dùng để tạo một phần tử điều hướng.',
                    'blanks' => 'p,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ nghiêng và thẻ [blank_2] dùng để tạo một vùng chọn trong biểu mẫu.',
                    'blanks' => 'em,select',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử có chú thích và thẻ [blank_2] tạo một khu vực chứa các phần tử.',
                    'blanks' => 'mark,section',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một khối văn bản có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử văn bản có kiểu chữ gạch chân và thẻ [blank_2] tạo một khu vực điều hướng.',
                    'blanks' => 'u,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để tạo một phần tử đầu trang.',
                    'blanks' => 's,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh và thẻ [blank_2] tạo một khu vực chứa các phần tử.',
                    'blanks' => 'strong,section',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một khu vực cho phần tử chính và thẻ [blank_2] định nghĩa phần tử có chú thích.',
                    'blanks' => 'main,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có kiểu chữ gạch chân và thẻ [blank_2] dùng để định nghĩa phần tử chân của tài liệu.',
                    'blanks' => 'u,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử văn bản có kiểu chữ nghiêng và thẻ [blank_2] tạo một danh sách không có thứ tự.',
                    'blanks' => 'em,ul',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để tạo một phần tử đầu trang.',
                    'blanks' => 's,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để định nghĩa một phần tử có chú thích.',
                    'blanks' => 'strong,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử đầu trang của tài liệu và thẻ [blank_2] dùng để định nghĩa phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khu vực chứa các phần tử và thẻ [blank_2] dùng để tạo một danh sách có thứ tự.',
                    'blanks' => 'section,ol',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có kiểu chữ gạch chân và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ gạch chéo.',
                    'blanks' => 'u,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử văn bản có kiểu chữ mạnh và thẻ [blank_2] tạo một khối văn bản có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có chú thích và thẻ [blank_2] tạo một phần tử đầu trang.',
                    'blanks' => 'mark,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực điều hướng và thẻ [blank_2] dùng để định nghĩa phần tử chân của tài liệu.',
                    'blanks' => 'nav,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một danh sách không có thứ tự và thẻ [blank_2] định nghĩa một nhóm các phần tử văn bản.',
                    'blanks' => 'ul,div',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực điều hướng và thẻ [blank_2] dùng để tạo một danh sách có thứ tự.',
                    'blanks' => 'nav,ol',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có kiểu chữ gạch chân và thẻ [blank_2] dùng để định nghĩa một phần tử đầu trang của tài liệu.',
                    'blanks' => 'u,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có kiểu chữ nghiêng và thẻ [blank_2] dùng để định nghĩa phần tử có kiểu chữ mạnh.',
                    'blanks' => 'em,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các mục trong danh sách không có thứ tự và thẻ [blank_2] dùng để tạo phần tử văn bản có kiểu chữ gạch chéo.',
                    'blanks' => 'ul,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử điều hướng và thẻ [blank_2] dùng để tạo một danh sách có thứ tự.',
                    'blanks' => 'nav,ol',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử đầu trang và thẻ [blank_2] dùng để tạo một khối văn bản có kiểu chữ gạch chân.',
                    'blanks' => 'header,u',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một phần tử có chú thích.',
                    'blanks' => 'strong,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] được sử dụng để tạo bảng và định nghĩa cột tiêu đề.',
                    'blanks' => 'table,th',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một nhóm liên kết điều hướng, thẻ [blank_2] định nghĩa một liên kết và thuộc tính [blank_3] xác định cách liên kết được mở.',
                    'blanks' => 'nav,a,target',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] được sử dụng để tạo form và định nghĩa các điều khiển nhập liệu như ô nhập và nút gửi.',
                    'blanks' => 'form,input',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn hình ảnh và thuộc tính [blank_2] xác định nguồn của hình ảnh.',
                    'blanks' => 'img,src',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa phần tử video và thuộc tính [blank_2] xác định nguồn video.',
                    'blanks' => 'video,src',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử khối văn bản và thẻ [blank_2] để tạo phần tử nội tuyến.',
                    'blanks' => 'div,span',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo danh sách không có thứ tự và các mục trong danh sách đó.',
                    'blanks' => 'ul,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử điều hướng và thuộc tính [blank_2] xác định cách liên kết mở.',
                    'blanks' => 'nav,target',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một đoạn văn bản với kiểu chữ mạnh và nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một nhóm các phần tử và thẻ [blank_2] tạo một nhóm các liên kết điều hướng.',
                    'blanks' => 'div,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một bảng và thẻ [blank_2] dùng để định nghĩa hàng trong bảng.',
                    'blanks' => 'table,tr',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa phần chân của tài liệu và thẻ [blank_2] dùng để định nghĩa phần đầu trang của tài liệu.',
                    'blanks' => 'footer,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo các mục trong danh sách có thứ tự và các mục trong danh sách đó.',
                    'blanks' => 'ol,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có chú thích và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ gạch chân.',
                    'blanks' => 'mark,u',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các liên kết và thẻ [blank_2] định nghĩa một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'nav,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một vùng chọn trong biểu mẫu và thẻ [blank_2] dùng để định nghĩa các tùy chọn trong vùng chọn.',
                    'blanks' => 'select,option',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực văn bản và thẻ [blank_2] dùng để tạo một khối văn bản có kiểu chữ mạnh.',
                    'blanks' => 'section,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử đầu trang và thẻ [blank_2] dùng để định nghĩa một phần tử điều hướng.',
                    'blanks' => 'header,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử và thẻ [blank_2] dùng để tạo một khối văn bản với kiểu chữ gạch chéo.',
                    'blanks' => 'div,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một vùng chứa các phần tử văn bản và thẻ [blank_2] dùng để tạo một bảng.',
                    'blanks' => 'section,table',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một nhóm các liên kết và các mục trong danh sách.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử văn bản có kiểu chữ gạch chân và thẻ [blank_2] dùng để tạo một phần tử đầu trang của tài liệu.',
                    'blanks' => 'u,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một phần tử có chú thích.',
                    'blanks' => 's,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một danh sách không có thứ tự và thẻ [blank_2] dùng để tạo các mục trong danh sách đó.',
                    'blanks' => 'ul,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một vùng chọn trong biểu mẫu và thẻ [blank_2] dùng để định nghĩa các tùy chọn trong vùng chọn.',
                    'blanks' => 'select,option',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một bảng và thẻ [blank_2] dùng để định nghĩa cột tiêu đề.',
                    'blanks' => 'table,th',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và các mục trong phần tử điều hướng đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một khu vực văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một nhóm các liên kết và các mục trong nhóm đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một vùng chứa văn bản và thẻ [blank_2] dùng để định nghĩa một bảng.',
                    'blanks' => 'section,table',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các mục trong danh sách có thứ tự và thẻ [blank_2] dùng để định nghĩa các mục đó.',
                    'blanks' => 'ol,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khối văn bản có kiểu chữ gạch chân và thẻ [blank_2] dùng để định nghĩa một phần tử đầu trang.',
                    'blanks' => 'u,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử có kiểu chữ nghiêng và thẻ [blank_2] dùng để tạo một vùng chứa các phần tử.',
                    'blanks' => 'em,section',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và các mục trong phần tử điều hướng đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản với kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một phần tử có chú thích.',
                    'blanks' => 's,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử văn bản và thẻ [blank_2] dùng để tạo một phần tử điều hướng.',
                    'blanks' => 'div,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một vùng chứa và thẻ [blank_2] dùng để tạo một danh sách không có thứ tự.',
                    'blanks' => 'section,ul',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chân và thẻ [blank_2] dùng để định nghĩa một phần tử có chú thích.',
                    'blanks' => 'u,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử điều hướng và thẻ [blank_2] dùng để định nghĩa một khối văn bản.',
                    'blanks' => 'nav,div',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ nghiêng và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh.',
                    'blanks' => 'em,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một vùng chứa và thẻ [blank_2] dùng để tạo một phần tử điều hướng.',
                    'blanks' => 'section,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một bảng và thẻ [blank_2] dùng để định nghĩa hàng trong bảng.',
                    'blanks' => 'table,tr',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một danh sách có thứ tự và thẻ [blank_2] dùng để định nghĩa các mục trong danh sách đó.',
                    'blanks' => 'ol,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử văn bản và thẻ [blank_2] dùng để tạo một phần tử đầu trang của tài liệu.',
                    'blanks' => 'div,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và các mục trong điều hướng đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử có kiểu chữ nghiêng và thẻ [blank_2] dùng để tạo một phần tử có chú thích.',
                    'blanks' => 'em,mark',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử đầu trang và thẻ [blank_2] dùng để định nghĩa một phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và các mục trong phần tử điều hướng đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chân và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'u,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một nhóm các phần tử và thẻ [blank_2] dùng để tạo một danh sách có thứ tự.',
                    'blanks' => 'div,ol',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một khối văn bản và một phần tử đầu trang của tài liệu.',
                    'blanks' => 'div,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khu vực điều hướng trong trang web và thẻ [blank_2] dùng để tạo các liên kết điều hướng bên trong khu vực đó.',
                    'blanks' => 'nav,a',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một biểu mẫu và thuộc tính [blank_2] của thẻ [blank_3] xác định nơi gửi dữ liệu.',
                    'blanks' => 'form,action,input',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] được sử dụng để tạo một bảng với các hàng và cột, và thẻ [blank_3] dùng để định nghĩa các cột trong bảng.',
                    'blanks' => 'table,tr,td',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn hình ảnh và thuộc tính [blank_2] xác định nguồn hình ảnh, thuộc tính [blank_3] xác định văn bản thay thế.',
                    'blanks' => 'img,src,alt',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các liên kết điều hướng và thẻ [blank_2] dùng để định nghĩa các mục trong nhóm liên kết đó.',
                    'blanks' => 'nav,ul',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một danh sách không có thứ tự với các mục trong danh sách đó.',
                    'blanks' => 'ul,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khối văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một khối văn bản có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để định nghĩa một khu vực chứa văn bản và thẻ [blank_3] dùng để tạo một khu vực cho biểu mẫu.',
                    'blanks' => 'section,article,form',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] định nghĩa một vùng chứa cho các mục trong danh sách có thứ tự và thẻ [blank_3] định nghĩa từng mục trong danh sách.',
                    'blanks' => 'ol,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] được sử dụng để tạo một phần tử có kiểu chữ mạnh và phần tử có kiểu chữ gạch chéo.',
                    'blanks' => 'strong,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn video vào trang web và thuộc tính [blank_2] xác định nguồn video, thuộc tính [blank_3] xác định các điều khiển phát video.',
                    'blanks' => 'video,src,controls',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một nhóm các tùy chọn trong biểu mẫu và thẻ [blank_2] dùng để định nghĩa từng tùy chọn trong nhóm đó.',
                    'blanks' => 'select,option',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một vùng chứa với kiểu chữ mạnh và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ gạch chéo.',
                    'blanks' => 'strong,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để định nghĩa các phần tử văn bản có kiểu chữ mạnh và phần tử văn bản có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử đầu trang và một phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một nhóm các mục trong danh sách không có thứ tự và thẻ [blank_2] định nghĩa từng mục trong nhóm đó.',
                    'blanks' => 'ul,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử đầu trang và thẻ [blank_2] dùng để tạo một phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các phần tử với kiểu chữ gạch chân và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'u,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khu vực văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để định nghĩa một khu vực điều hướng.',
                    'blanks' => 'strong,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để chèn hình ảnh vào trang và thuộc tính [blank_2] xác định văn bản thay thế cho hình ảnh.',
                    'blanks' => 'img,alt',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử khối và thẻ [blank_2] dùng để định nghĩa một phần tử điều hướng.',
                    'blanks' => 'div,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một nhóm các liên kết điều hướng và thẻ [blank_2] dùng để định nghĩa từng liên kết trong nhóm đó.',
                    'blanks' => 'nav,a',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] được sử dụng để tạo một khu vực chứa và định nghĩa các mục trong danh sách có thứ tự.',
                    'blanks' => 'section,ol',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một phần tử có kiểu chữ mạnh và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh và một phần tử có kiểu chữ gạch chéo.',
                    'blanks' => 'strong,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử đầu trang và thẻ [blank_2] dùng để định nghĩa phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một nhóm các liên kết điều hướng và các mục trong nhóm đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một khối văn bản có kiểu chữ nghiêng và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh.',
                    'blanks' => 'em,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ nghiêng.',
                    'blanks' => 's,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử điều hướng và thẻ [blank_2] dùng để định nghĩa một khối văn bản có kiểu chữ gạch chân.',
                    'blanks' => 'nav,u',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử đầu trang và thẻ [blank_2] dùng để định nghĩa một phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh và một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một khối văn bản có kiểu chữ gạch chéo và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và một phần tử đầu trang.',
                    'blanks' => 'nav,header',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một vùng chứa và thẻ [blank_2] dùng để tạo một phần tử điều hướng.',
                    'blanks' => 'section,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử khối và thẻ [blank_2] dùng để định nghĩa một nhóm các liên kết.',
                    'blanks' => 'div,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử có kiểu chữ nghiêng và một phần tử có kiểu chữ mạnh.',
                    'blanks' => 'em,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một nhóm các phần tử điều hướng và thẻ [blank_2] dùng để định nghĩa các mục trong nhóm đó.',
                    'blanks' => 'nav,li',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử đầu trang và một phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để định nghĩa một khối văn bản có kiểu chữ mạnh và thẻ [blank_2] dùng để tạo một phần tử có kiểu chữ gạch chéo.',
                    'blanks' => 'strong,s',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh và một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 's,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và một khối văn bản có kiểu chữ mạnh.',
                    'blanks' => 'nav,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để định nghĩa một phần tử có kiểu chữ gạch chéo và một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử đầu trang và thẻ [blank_2] dùng để tạo một phần tử điều hướng.',
                    'blanks' => 'header,nav',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử có kiểu chữ mạnh và một phần tử có kiểu chữ nghiêng.',
                    'blanks' => 'strong,em',
                ],
                [
                    'question' => 'Thẻ [blank_1] dùng để tạo một phần tử đầu trang và thẻ [blank_2] dùng để định nghĩa phần tử chân của tài liệu.',
                    'blanks' => 'header,footer',
                ],
                [
                    'question' => 'Thẻ [blank_1] định nghĩa một phần tử có kiểu chữ gạch chéo và thẻ [blank_2] dùng để định nghĩa một phần tử có kiểu chữ mạnh.',
                    'blanks' => 's,strong',
                ],
                [
                    'question' => 'Thẻ [blank_1] và [blank_2] dùng để tạo một phần tử điều hướng và một phần tử đầu trang của tài liệu.',
                    'blanks' => 'nav,header',
                ],
            ];
    }





    public function run(): void
    {
        //
    }
}
